- name: Kaynak Kodunu İndir (Repo Sync)
        run: |
          mkdir workspace
          cd workspace
          
          # Git'in dizin kısıtlamalarını kaldır (Exit Code 5 için ilaç)
          git config --global --add safe.directory '*'
          
          # Git kimlik ayarları
          git config --global user.name "EFE521"
          git config --global user.email "efe@gmail.com"
          
          # GitHub başlıklarını temizle
          git config --global --unset-all http.https://github.com/.extraheader
          
          # Repo aracını kur ve Python3'e bağla
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          chmod a+x repo
          sudo mv repo /usr/local/bin/
          
          # Bazı sistemlerde 'python' komutu yoktur, 'python3' vardır. Repo için bunu düzeltiyoruz.
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          
          # Repo başlatma - anonim erişim
          repo init -u https://github.com/minimal-twrp-omni/platform_manifest_twrp_omni.git -b twrp-11 --depth=1 --no-clone-bundle
          
          # Senkronizasyon
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
